<?php
/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-01-16 at 07:27:36.
 */
class MonoTest extends PHPUnit_Framework_TestCase
{
    protected $ob;

    protected function setUp()
    {
        $this->ob = new Mono;
    }

    protected function rollMany($n, $pins)
    {
        for ($i = 0; $i < $n; $i++) {
            $this->ob->roll($pins);
        }
    }

    public function testScoreForGutterGameIs0()
    {
        $this->rollMany(20, 0);
        $this->assertEquals(0, $this->ob->score());
    }
}
